### ISSUE TITLE
JDK 11 issue?

### ISSUE THREAD

**Issue by knyttl** [todvora/eet-client#41]
I had to add following dependencies to my project to run it on JDK 11:

```
        <dependency>
            <groupId>javax.xml.ws</groupId>
            <artifactId>jaxws-api</artifactId>
            <version>2.3.1</version>
        </dependency>
        <dependency>
            <groupId>com.sun.xml.ws</groupId>
            <artifactId>jaxws-ri</artifactId>
            <version>2.3.2</version>
        </dependency>
        <dependency>
            <groupId>javax.activation</groupId>
            <artifactId>javax.activation-api</artifactId>
            <version>1.2.0</version>
        </dependency>
        <dependency>
            <groupId>com.sun.xml.messaging.saaj</groupId>
            <artifactId>saaj-impl</artifactId>
            <version>1.5.1</version>
        </dependency>
```

However during reporting I still get: 
```
 org.apache.cxf.phase.PhaseInterceptorChain.doDefaultLogging Interceptor for {http://fs.mfcr.cz/eet/schema/v3}EETService#{http://fs.mfcr.cz/eet/schema/v3}OdeslaniTrzby has thrown exception, unwinding now
	org.w3c.dom.DOMException: WRONG_DOCUMENT_ERR: A node is used in a different document than the one that created it.
		at java.xml/com.sun.org.apache.xerces.internal.dom.ParentNode.internalInsertBefore(ParentNode.java:356)
		at java.xml/com.sun.org.apache.xerces.internal.dom.ParentNode.insertBefore(ParentNode.java:287)
		at java.xml/com.sun.org.apache.xerces.internal.dom.NodeImpl.appendChild(NodeImpl.java:237)
		at org.apache.wss4j.dom.util.WSSecurityUtil.prependChildElement(WSSecurityUtil.java:709)
		at org.apache.wss4j.dom.util.WSSecurityUtil.findWsseSecurityHeaderBlock(WSSecurityUtil.java:803)
		at org.apache.wss4j.dom.message.WSSecHeader.insertSecurityHeader(WSSecHeader.java:134)
		at org.apache.wss4j.dom.handler.WSHandler.doSenderAction(WSHandler.java:101)
		at org.apache.cxf.ws.security.wss4j.WSS4JOutInterceptor.access$100(WSS4JOutInterceptor.java:54)
		at org.apache.cxf.ws.security.wss4j.WSS4JOutInterceptor$WSS4JOutInterceptorInternal.handleMessageInternal(WSS4JOutInterceptor.java:267)
		at org.apache.cxf.ws.security.wss4j.WSS4JOutInterceptor$WSS4JOutInterceptorInternal.handleMessage(WSS4JOutInterceptor.java:135)
		at org.apache.cxf.ws.security.wss4j.WSS4JOutInterceptor$WSS4JOutInterceptorInternal.handleMessage(WSS4JOutInterceptor.java:122)
		at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
		at org.apache.cxf.endpoint.ClientImpl.doInvoke(ClientImpl.java:516)
		at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:425)
		at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:326)
		at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:279)
		at org.apache.cxf.frontend.ClientProxy.invokeSync(ClientProxy.java:96)
		at org.apache.cxf.jaxws.JaxWsClientProxy.invoke(JaxWsClientProxy.java:138)
		at com.sun.proxy.$Proxy181.odeslaniTrzby(Unknown Source)
		at cz.tomasdvorak.eet.client.EETClientImpl.sendSync(EETClientImpl.java:61)
```

**Comment by pilec** [comment]
Hello, it's been fixed by https://github.com/todvora/eet-client/pull/42
