### ISSUE TITLE
Error during certificate path validation

### ISSUE THREAD

**Issue by Lainiel** [todvora/eet-client#5]
I'm unable to generate FIK and BKP, because I get the following warning.
I've tried installing the I.CA Root certificate with keytool, but that didn't help.
I'm using the example code in the Usage section in readme.
Thanks for any help.

WARNING: Interceptor for {http://fs.mfcr.cz/eet/schema/v3}EETService#{http://fs.mfcr.cz/eet/schema/v3}OdeslaniTrzby has thrown exception, unwinding now
org.apache.cxf.binding.soap.SoapFault: Error during certificate path validation: No trusted certs found
	at org.apache.cxf.ws.security.wss4j.WSS4JUtils.createSoapFault(WSS4JUtils.java:277)
	at org.apache.cxf.ws.security.wss4j.WSS4JInInterceptor.handleMessageInternal(WSS4JInInterceptor.java:333)
	at org.apache.cxf.ws.security.wss4j.WSS4JInInterceptor.handleMessage(WSS4JInInterceptor.java:190)
	at cz.tomasdvorak.eet.client.security.SecureEETCommunication$1.handleMessage(SecureEETCommunication.java:135)
	at cz.tomasdvorak.eet.client.security.SecureEETCommunication$1.handleMessage(SecureEETCommunication.java:119)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
	at org.apache.cxf.endpoint.ClientImpl.onMessage(ClientImpl.java:802)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponseInternal(HTTPConduit.java:1673)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponse(HTTPConduit.java:1551)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.close(HTTPConduit.java:1348)
	at org.apache.cxf.io.CacheAndWriteOutputStream.postClose(CacheAndWriteOutputStream.java:56)
	at org.apache.cxf.io.CachedOutputStream.close(CachedOutputStream.java:215)
	at org.apache.cxf.transport.AbstractConduit.close(AbstractConduit.java:56)
	at org.apache.cxf.transport.http.HTTPConduit.close(HTTPConduit.java:651)
	at org.apache.cxf.interceptor.MessageSenderInterceptor$MessageSenderEndingInterceptor.handleMessage(MessageSenderInterceptor.java:62)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
	at org.apache.cxf.endpoint.ClientImpl.doInvoke(ClientImpl.java:516)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:425)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:326)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:279)
	at org.apache.cxf.frontend.ClientProxy.invokeSync(ClientProxy.java:96)
	at org.apache.cxf.jaxws.JaxWsClientProxy.invoke(JaxWsClientProxy.java:138)
	at com.sun.proxy.$Proxy70.odeslaniTrzby(Unknown Source)
	at cz.tomasdvorak.eet.client.EETClientImpl.submitReceipt(EETClientImpl.java:35)
	at application.Main.main(Main.java:49)
Caused by: org.apache.wss4j.common.ext.WSSecurityException: Error during certificate path validation: No trusted certs found
	at org.apache.wss4j.common.crypto.Merlin.verifyTrust(Merlin.java:877)
	at cz.tomasdvorak.eet.client.security.MerlinWithCRLDistributionPointsExtension.verifyTrust(MerlinWithCRLDistributionPointsExtension.java:34)
	at org.apache.wss4j.dom.validate.SignatureTrustValidator.verifyTrustInCerts(SignatureTrustValidator.java:108)
	at org.apache.wss4j.dom.validate.SignatureTrustValidator.validate(SignatureTrustValidator.java:64)
	at org.apache.wss4j.dom.processor.SignatureProcessor.handleToken(SignatureProcessor.java:185)
	at org.apache.wss4j.dom.WSSecurityEngine.processSecurityHeader(WSSecurityEngine.java:428)
	at org.apache.cxf.ws.security.wss4j.WSS4JInInterceptor.handleMessageInternal(WSS4JInInterceptor.java:278)
	... 23 more

**Comment by todvora** [comment]
Hi, I will need more info: production or playground endpoint? Which certificate exactly are you using (filename, which subject and issuer in it)? Could you share content of the BinarySecurityToken of the **response** (EET server public certificate, to be found in webservice.log)?

Thanks!
Tomas

**Comment by Lainiel** [comment]
At first I had a problem with playground, but I figured out I was using the wrong server Certificate, but now I have the same problem in the production endpoint.

I'm using this certificate:
http://www.ica.cz/userfiles/files/certifikaty/SHA2/qica_root_key_20090901.der

Here is the content of the BinartySecurityToken:

<wsse:BinarySecurityToken wsu:Id="SecurityToken-dcff09fe-50df-4fc5-98f2-d3702bd3520b" EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary" ValueType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-x509-token-profile-1.0#X509v3">MIIGajCCBFKgAwIBAgIEAKqDwjANBgkqhkiG9w0BAQsFADB/MQswCQYDVQQGEwJDWjEoMCYGA1UEAwwfSS5DQSBRdWFsaWZpZWQgMiBDQS9SU0EgMDIvMjAxNjEtMCsGA1UECgwkUHJ2bsOtIGNlcnRpZmlrYcSNbsOtIGF1dG9yaXRhLCBhLnMuMRcwFQYDVQQFEw5OVFJDWi0yNjQzOTM5NTAeFw0xNjEwMjUxMzE0NTdaFw0xNzEwMjUxMzE0NTdaMIGRMSYwJAYDVQQDDB1FbGVrdHJvbmlja8OhIGV2aWRlbmNlIHRyxb5lYjELMAkGA1UEBhMCQ1oxQTA/BgNVBAoMOMSMZXNrw6EgcmVwdWJsaWthIC0gR2VuZXLDoWxuw60gZmluYW7EjW7DrSDFmWVkaXRlbHN0dsOtMRcwFQYDVQQFEw5JQ0EgLSAxMDM4NDczNDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAJ+UCnx1Kb2VsZ0HvozKvx3I7dGkcV2kwEDtdzrmSeqkmMDk6LLKkmQAUYWd3GpV0YEa0ueWtFBWw3HB1joEoSUjrMLlIfcvCwi1QkfiufvRZXs/LA3eJU3lCD2rDsTE1V2kprAKqlATkye7m1c1SMOzp8ZiOVamH34hTsah+BCbN+P0BaQQGjPCtkRa35BDNcPuoT05MejyeQL239I4dgaR2UlYGRiG69yfigRYYp06wHaaYzmSeCqO8ei//Ob8BA2uSm1vO/8R8QOjmv3bnYPVRRnTZ27RqbFwQh5HFLsZ73KnKqRVnIcgXUPegUuY8yrfHOtFe4JlquAVBnVocP8CAwEAAaOCAdkwggHVMDgGA1UdEQQxMC+BE2Vwb2Rwb3JhQGZzLm1mY3IuY3qgGAYKKwYBBAGBuEgEBqAKDAgxMDM4NDczNDAOBgNVHQ8BAf8EBAMCBsAwRQYDVR0gBD4wPDAwBg0rBgEEAYG4SAoBIQEAMB8wHQYIKwYBBQUHAgEWEWh0dHA6Ly93d3cuaWNhLmN6MAgGBgQAj3oBATCBjwYDVR0fBIGHMIGEMCqgKKAmhiRodHRwOi8vcWNybGRwMS5pY2EuY3ovMnFjYTE2X3JzYS5jcmwwKqAooCaGJGh0dHA6Ly9xY3JsZHAyLmljYS5jei8ycWNhMTZfcnNhLmNybDAqoCigJoYkaHR0cDovL3FjcmxkcDMuaWNhLmN6LzJxY2ExNl9yc2EuY3JsMGUGCCsGAQUFBwEBBFkwVzAqBggrBgEFBQcwAoYeaHR0cDovL3EuaWNhLmN6LzJxY2ExNl9yc2EuY2VyMCkGCCsGAQUFBzABhh1odHRwOi8vb2NzcC5pY2EuY3ovMnFjYTE2X3JzYTAJBgNVHRMEAjAAMB0GA1UdDgQWBBR/GZkmy8LPnWEZPkzHc2U65Nw1BTAfBgNVHSMEGDAWgBR0ggiR49lkaHGF1usx5HLfiyaxbTANBgkqhkiG9w0BAQsFAAOCAgEAViZN9/+XngmZ+kubBf13tov2mlHNXYs3pswu+06I9EOoscZDMXCceVRi50aUv5cbJmEb6P65+EiFB8ZfH8coxBTFe0+xVR7e3kJ+HpQtAmvjbkwBDvWSzS5RSozTpj0CEdfqpWkocJdlX1AYJhHsDtAJzdX0tXHOOgfqUl8qJ+kGeB/X2gt7/f5ODgy+V6OR6aQDYdX0ymg99YN8hLyJBO8K259t5TWNZBEmvwHyXsPd5UzoKU/FheR0VFawSUOFrdcKWWDPbHzHoVZ4xMFh+LPHJns9v7lQdAmb/TVNUvwQwD8t3hh1PR+DH9KL/DDD0utgApCGf2E6fy5lo8xOSXTTHGcOvYdAHx5+mVKph4WEw2CiqP6si0oOWLI1DaZUwC+2U0CwOjlK7+S59FocQ9+DK/vtnfC1z5bXCvKMpgEdHGaV02OZWMvbluAqBZQlkEUnQkAx0pOvK8cY3vSoEXJDeFy62HvFIydAR8nriFbuKha5BiAwI6JN0Ari0+E/Vxqhvu273UoonQcgi/ymBy7mZ2w/Uy5M2+QamCYag/B9dGapJnvk2T00bwpAOsvEyI1fYOqDpOLDRCU/9bmS3qcctg//LSS18s1Z93p5vfRx7LoqFOXhagXWIrX2YU+TqN8EtCyhZSoGzo7zaacz2XWWQh86AbkHGi6i42YVfpY=</wsse:BinarySecurityToken>

**Comment by todvora** [comment]
Could you try this I.CA root certificate against the production endpoint? http://www.ica.cz/userfiles/files/certifikaty/HCA_kvalifikovany/2qca16_rsa.der

I think they are using two different CA's for the communication. But I don't have any production klient keys to be able to test that. 

Thanks!

**Comment by marek-veber** [comment]
The site https://prod.eet.cz/ is issued by this certificate:
{subject='CN=GeoTrust Extended Validation SHA256 SSL CA, O=GeoTrust Inc., C=US', issuer='CN=GeoTrust Primary Certification Authority - G3, OU=(c) 2008 GeoTrust Inc. - For authorized use only, O=GeoTrust Inc., C=US', SerialNumber=111783015348261377250807606752936718522, validFrom=2013-04-09T02:00:00+02:00, validTo=2023-04-09T01:59:59+02:00}

For java-8-oracle  Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files 8 must be used (I have tested that ubuntu java-8-openjdk don't needs this) , see: http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html

**Comment by marek-veber** [comment]
Sorry for my previous offtopic comment, default java truststore is used for https ;(

But check attached testcase (see the exception in testCrlProduction):
[eet-production-error.zip](https://github.com/todvora/eet-client/files/601756/eet-production-error.zip)

This issue comes on production when checking returned signature (workarroud is to skip CRL checking on production environment).

**Comment by todvora** [comment]
Hi @marek-veber,
Thank you for your test case. With your help I've been finally able to figure it out. There are basically two different issues:

## Two CA certificates are needed in production
The production certificate is issued by ```SERIALNUMBER=NTRCZ-26439395, O="První certifikační autorita, a.s.", CN=I.CA Qualified 2 CA/RSA 02/2016, C=CZ```. To be able to validate it, [2qca16_rsa.der](http://www.ica.cz/userfiles/files/certifikaty/HCA_kvalifikovany/2qca16_rsa.der) (Qualified system certificate subordinate QCA (CN = I.CA Qualified 2 CA/RSA 02/2016 sn:  100001006/0x5f5e4ee)) is needed.

But this is just a subordinate CA. So we need to add a root CA too: [rca15_rsa.der](www.ica.cz/userfiles/files/certifikaty/HCA_root/rca15_rsa.der) (Qualified system certificate root CA (CN = I.CA Root CA/RSA,  sn:  100000000/0x5f5e100)).

With both this certificates, we are able to verify the whole chain down to the root. This is different to playground, where the EET PG certificate is issued directly by the root CA ([qica_root_key_20090901.der](www.ica.cz/userfiles/files/certifikaty/SHA2/qica_root_key_20090901.der)).

## CRLs of subordinate CA has to be checked
The ```MerlinWithCRLDistributionPointsExtension``` class imported automatically only the CRLs provided by the CA, which issued the cert. But we need to validate CRLs of the whole chain, including CRLs of root CA, which issues the subordinate QCA certificate.

All the tests are passing now, with validation and CRLs checking enabled. It's needed to update eet-client to ```2.0.0``` release and provide additional certificates to the library:

```java
InputStream clientKey = getClass().getResourceAsStream("/keys/CZ683555118.p12");
InputStream rootCACertificate = getClass().getResourceAsStream("/keys/rca15_rsa.der");
InputStream subordinateCACertificate = getClass().getResourceAsStream("/keys/2qca16_rsa.der");
EETClient client = EETServiceFactory.getInstance(clientKey, "eet", rootCACertificate, subordinateCACertificate);
```

Could you please test this client version and setup against production endpoint?

Thank you very much!
Tomas

**Comment by marek-veber** [comment]
Nice work, it works for me ! (on oracle java there is need of JCE).
Sorry for the my incomplete report - I knowed about the needs of two certificates (root&intermediate) - I have solved it by the same way as You, sorry again. To solve the CLR check - it needs more than my knowledge ;) Thanks for solving it.

I have another issue which was just solved by me, I will open it separatelly.

**Comment by todvora** [comment]
Hi @Lainiel,
Any feedback? Does it work for you now? May I close this issue as resolved?

Thanks,
Tomas

**Comment by todvora** [comment]
Closing due to inactivity. Feel free to reopen in case of any problems.
